#!/bin/bash -xe

TMP_DIR="`mktemp -d`"
SVN_DIR="/var/www/svn"
REPO="${SVN_DIR}/test"

ID="00000000-0000-0000-0000-000000000000"
BASE="${TMP_DIR}/trunk/${ID}"
COPY="${BASE}/copy"
MOVE="${BASE}/move"

mkdir -p ${SVN_DIR}
rm -rf   ${REPO}
svnadmin create ${REPO}
svn co file://${REPO} "${TMP_DIR}"

# create structure {{{1
mkdir   "${TMP_DIR}/tags" "${TMP_DIR}/branches" "${TMP_DIR}/trunk"
svn add "${TMP_DIR}/tags"
svn add "${TMP_DIR}/branches"
svn add "${TMP_DIR}/trunk"
svn ci  "${TMP_DIR}" -m "create SVN structure"

mkdir   "${BASE}"
mkdir   "${BASE}/folder_empty"
mkdir   "${BASE}/folder_with_files"
touch   "${BASE}/folder_with_files/a.txt"
touch   "${BASE}/folder_with_files/b.txt"
touch   "${BASE}/folder_with_files/c.txt"
touch   "${BASE}/folder_with_files/d.txt"
mkdir   "${BASE}/folder_with_dirs"
mkdir   "${BASE}/folder_with_dirs/a"
mkdir   "${BASE}/folder_with_dirs/b"
mkdir   "${BASE}/folder_with_dirs/c"
mkdir   "${BASE}/folder_with_dirs/d"
mkdir   "${BASE}/folder_mixed"
touch   "${BASE}/folder_mixed/file.txt"
mkdir   "${BASE}/folder_mixed/a"
touch   "${BASE}/folder_mixed/a/file.txt"
mkdir   "${BASE}/folder_mixed/a/b"
touch   "${BASE}/folder_mixed/a/b/file.txt"
svn add "${BASE}"
svn ci  "${TMP_DIR}" -m "create test structure"
svn cp  file://${REPO}/trunk file://${REPO}/tags/0.0 -m "release 0.0"

# create properties {{{1
for ((i=1; i<=5; i++)); do
svn propset myProperty "value ${i}" "${BASE}/folder_mixed/file.txt"
svn ci "${TMP_DIR}" -m "changeing myProperty ${i}"
done

for ((i=1; i<=5; i++)); do
svn propset "myProperty${i}" "value ${i}" "${BASE}/folder_mixed/a/file.txt"
svn ci "${TMP_DIR}" -m "adding myProperty${i}"
done

# create 10 tags with changes in revisions.txt {{{1
cat >   "${BASE}/revisions.txt" <<EOF
Test 1
EOF
svn add "${BASE}/revisions.txt"
svn ci  "${TMP_DIR}" -m "adding revisions file 1"
svn cp  file://${REPO}/trunk file://${REPO}/tags/1.0 -m "release 1.0"

for ((i=2; i<=9; i++)); do
cat >   "${BASE}/revisions.txt" <<EOF
Test ${i}
EOF
svn ci  "${TMP_DIR}" -m "adding revisions file ${i}"
svn cp  file://${REPO}/trunk file://${REPO}/tags/${i}.0 -m "release ${i}.0"
done

# create testcases for commit id {{{1
mkdir   "${COPY}"
svn add "${COPY}"
svn ci  "${TMP_DIR}" -m "created move folder"

svn cp  "${BASE}/folder_empty" "${COPY}/folder_empty"
svn ci  "${TMP_DIR}" -m "copy of empty folder"

svn cp  "${BASE}/folder_with_dirs" "${COPY}/folder_with_dirs"
svn ci  "${TMP_DIR}" -m "copy of folder with dirs"

svn cp  "${BASE}/folder_with_files" "${COPY}/folder_with_files"
svn ci  "${TMP_DIR}" -m "copy of folder with files"

svn cp  "${BASE}/folder_mixed" "${COPY}/folder_mixed"
svn ci  "${TMP_DIR}" -m "copy of mixed folder"

svn cp  "${COPY}/folder_mixed/file.txt" "${COPY}/folder_mixed/file-copy.txt"
svn ci  "${TMP_DIR}" -m "copy of file"

svn cp  "${COPY}/folder_mixed" "${COPY}/folder_mixed2"
svn ci  "${TMP_DIR}" -m "copy of copy"

# create resolving testcases {{{1
mkdir   "${MOVE}"
svn add "${MOVE}"
svn ci  "${TMP_DIR}" -m "created move folder"

svn cp  "${BASE}/folder_mixed" "${MOVE}/folder_mixed"
svn ci  "${TMP_DIR}" -m "copy of mixed folder"

svn mv  "${MOVE}/folder_mixed/file.txt" "${MOVE}/folder_mixed/file-0.txt"
svn ci  "${TMP_DIR}" -m "just rename to file-0.txt"

svn mv  "${MOVE}/folder_mixed/file-0.txt" "${MOVE}/folder_mixed/file-1.txt"
svn ci  "${TMP_DIR}" -m "just rename to file-1.txt"
cat >   "${MOVE}/folder_mixed/file-1.txt" <<EOF
Test 1
EOF
svn ci  "${TMP_DIR}" -m "modified file-1.txt"

svn mv  "${MOVE}/folder_mixed/a" "${MOVE}/folder_mixed/a-0"
svn ci  "${TMP_DIR}" -m "just rename to a-0"

cat >>  "${MOVE}/folder_mixed/a-0/file.txt" <<EOF
new content
EOF
svn ci  "${TMP_DIR}" -m "modified"

cat >>  "${MOVE}/folder_mixed/a-0/b/file.txt" <<EOF
content
EOF
svn ci  "${TMP_DIR}" -m "modified"

#svn mv  "${MOVE}/folder_mixed/a-0/b" "${MOVE}/folder_mixed/a-0/b-0"
svn mv  --parents "${MOVE}/folder_mixed/a-0/b/file.txt" "${MOVE}/folder_mixed/a-0/b-0/file-0.txt"
svn ci  "${TMP_DIR}" -m "moved folder + file"

# create branches {{{1
svn cp  file://${REPO}/tags/2.0 file://${REPO}/branches/2.x -m "branche 2.x"
svn cp  file://${REPO}/tags/5.0 file://${REPO}/branches/5.x -m "branche 5.x"
svn cp  file://${REPO}/tags/8.0 file://${REPO}/branches/8.x -m "branche 8.x"

svn up  "${TMP_DIR}"

# modify branches {{{1
cat >   "${TMP_DIR}/branches/2.x/${ID}/revisions.txt" <<EOF
empty
EOF
svn ci  "${TMP_DIR}" -m "modify revisions.txt on branch 2.x"
svn mv  "${TMP_DIR}/branches/5.x/${ID}/revisions.txt" "${TMP_DIR}/branches/5.x/${ID}/revisions_new.txt"
svn ci  "${TMP_DIR}" -m "rename revisions.txt on branch 5.x"
svn rm  "${TMP_DIR}/branches/8.x/${ID}/revisions.txt"
svn ci  "${TMP_DIR}" -m "remove revisions.txt on branch 8.x"

svn cp  file://${REPO}/branches/2.x file://${REPO}/tags/2.1 -m "branche 2.1"
svn cp  file://${REPO}/branches/5.x file://${REPO}/tags/5.1 -m "branche 5.1"
svn cp  file://${REPO}/branches/8.x file://${REPO}/tags/8.1 -m "branche 8.1"

svn mv  "${TMP_DIR}/branches/5.x/${ID}/revisions_new.txt" "${TMP_DIR}/branches/5.x/${ID}/revisions.txt"
svn ci  "${TMP_DIR}" -m "rename revisions.txt on branch 5.x"
svn cp  file://${REPO}/branches/5.x file://${REPO}/tags/5.2 -m "branche 5.2"

# cleanup {{{1
chown -R www-data:www-data ${SVN_DIR}
rm -rf "${TMP_DIR}"
