#!/bin/bash -e

TMP_DIR="`mktemp -d`"
LOCAL="${TMP_DIR}/local"
DUMP="${TMP_DIR}/dump"
BASE="${LOCAL}/trunk/00000000-0000-0000-0000-000000000000"

REPO="${TMP_DIR}/svn"

create_file() { #{{{1
	local file="${1}"
	local delete="${2}"

	mkdir -p `dirname "${file}"`
	local content
	for content in A B C; do
		echo "${content}" >                               "${file}"
		svn add     --quiet --parents                     "${file}"
		svn propset --quiet svn:mime-type text/plain      "${file}"
		svn propset --quiet modifiedProperty ${content}   "${file}"
		svn propset --quiet property${content} ${content} "${file}"
		commit "${file} with content: ${content}"         "${file}"
	done

	if [ "${delete}" -eq 1 ]; then
		# copy
		local copy=`echo ${file} | sed 's:delete:copy:g'`
		svn copy "${file}" "${copy}"
		commit "copied ${file} -> ${copy}" "${copy}"
		# move
		local tmp=`echo ${file} | sed 's:delete:tmp:g'`
		local move=`echo ${file} | sed 's:delete:move:g'`
		svn copy "${file}" "${tmp}"
		commit "copied ${file} -> ${tmp}" "${tmp}"
		svn mv "${tmp}" "${move}"
		commit "moved ${tmp} -> ${move}" "${move}"
		# delete
		rm -f "${file}"
		svn remove --quiet "${file}"
		commit "deleted ${file}" "${file}"
	fi
} #}}}1
create_folder() { #{{{1
	local folder="${1}"
	local delete="${2}"

	mkdir -p "${folder}"
	svn add     --quiet --parents                     "${folder}"
	svn propset --quiet svn:ignore "*.bin"            "${folder}"
	svn propset --quiet chustomProperty "test"        "${folder}"
	commit "created ${folder}" "${folder}"

	if [ "${delete}" -eq 1 ]; then
		# copy
		local copy=`echo ${folder} | sed 's:delete:copy:g'`
		svn copy "${folder}" "${copy}"
		commit "copied ${folder} -> ${copy}" "${copy}"
		# move
		local tmp=`echo ${folder} | sed 's:delete:tmp:g'`
		local move=`echo ${folder} | sed 's:delete:move:g'`
		svn copy "${folder}" "${tmp}"
		commit "copied ${folder} -> ${tmp}" "${tmp}"
		svn mv "${tmp}" "${move}"
		commit "moved ${tmp} -> ${move}" "${move}"
		# delete
		rm -rf "${folder}"
		svn remove --quiet "${folder}"
		commit "deleted ${folder}" "${folder}"
	fi
} #}}}1
commit() { #{{{1
	local message=${1}; shift
	message=`echo "${message}" | sed "s:${LOCAL}::g"`
	local resource
	for resource in $@; do
		svn add --parents --quiet "${resource}"
	done
	svn commit "${LOCAL}" --message "${message}"

	local version=`svn info "file://${REPO}" | grep ^Revision: | awk '{print $2}'`
	local src
	for src in `find "${LOCAL}" -not -wholename "*/.svn*"`; do
		local target=`echo "${src}" | sed "s:^${LOCAL}:${DUMP}/${version}:g"`
		if [ -d "${src}" ]; then
			mkdir -p "${target}"
		else
			cp "${src}" "${target}"
		fi
		if [ "${target}" = "${DUMP}/${version}" ]; then
			target="${target}/ROOT"
		fi

		local rsrc=`echo "${src}" | sed "s:^${LOCAL}:file\://${REPO}:g"`
		svn log                --xml "${rsrc}" | xmllint --format - | sed "s:${REPO}::g" | sed -E "s:[0-9]{3}Z</date>:Z</date>:g" > "${target}.log"
		svn info               --xml "${rsrc}" | xmllint --format - | sed "s:${REPO}::g" | sed -E "s:[0-9]{3}Z</date>:Z</date>:g" > "${target}.info"
		svn proplist --verbose --xml "${rsrc}" | xmllint --format - | sed "s:${REPO}::g"                                          > "${target}.proplist"
	done
} #}}}1

### init {{{1
mkdir -p "${REPO}" "${DUMP}"

svnadmin create "${REPO}"
svn checkout --quiet "file://${REPO}" "${LOCAL}"

### prepare repo {{{1
mkdir -p "${BASE}"
mkdir -p "${LOCAL}/branches"
mkdir -p "${LOCAL}/tags"
commit "create structure" "${BASE}" "${LOCAL}/branches" "${LOCAL}/tags"

# copy {{{1
create_file   "${BASE}/copy/file.txt" 0
create_file   "${BASE}/copy/file_delete.txt" 1
create_folder "${BASE}/copy/folder" 0
create_folder "${BASE}/copy/folder_delete" 1

# download {{{1
create_file "${BASE}/download/file.txt" 0
create_file "${BASE}/download/file_delete.txt" 1

# exists {{{1
create_file   "${BASE}/exists/file.txt" 0
create_file   "${BASE}/exists/file_delete.txt" 1
create_folder "${BASE}/exists/folder" 0
create_folder "${BASE}/exists/folder_delete" 1

# info {{{1
# TODO properties
create_file   "${BASE}/info/file.txt" 0
create_file   "${BASE}/info/file_delete.txt" 1
create_folder "${BASE}/info/folder" 0
create_folder "${BASE}/info/folder_delete" 1

# list {{{1
create_file   "${BASE}/list/file.txt" 0
create_file   "${BASE}/list/file_delete.txt" 1
create_folder "${BASE}/list/folder" 0
create_folder "${BASE}/list/folder_delete" 1

# lock {{{1
mkdir -p      "${BASE}/lock"
echo A >      "${BASE}/lock/file.txt"
commit        "${BASE}/lock/file.txt with content: A" "${BASE}/lock/file.txt"
echo B >      "${BASE}/lock/file.txt"
svn lock      "${BASE}/lock/file.txt"
commit        "${BASE}/lock/file.txt with content: B + lock" "${BASE}/lock/file.txt"

# log {{{1
create_file   "${BASE}/log/file.txt" 0
create_file   "${BASE}/log/file_delete.txt" 1

### package {{{1
cd "${TMP_DIR}"
for i in dump svn; do
	zip_file="${i}.zip"
	zip --quiet --recurse-paths "${zip_file}" "${i}"
	md5sum  "${zip_file}" > "${zip_file}.md5"
	sha1sum "${zip_file}" > "${zip_file}.sha1"
done

chown -R www-data:www-data ${REPO}
mv svn test

### cleanup {{{1
rm -rf        /tmp/svn
mv ${TMP_DIR} /tmp/svn
chmod 0755    /tmp/svn
